[service]
port = 8044
disk_ram = true
llhls = true
[rtmp]
port = 1930
[docker]
mode=false
[mp4]
record=false
[ebml]
record=false
[s3]
access=""
secret=""
region="ap-northeast-2"
cache_control="CDN-Cache-Control"